spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wialon_transport
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
    show-sql: true
  kafka:
    bootstrap-servers: 127.0.0.1:9092
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

protocol-server:
  new-wing:
    host: localhost
    port: 6001
    thread-count-processing-connection: 1
    thread-count-processing-data: 10
    connection-life-timeout-seconds: 300
  wialon:
    host: localhost
    port: 6002
    thread-count-processing-connection: 1
    thread-count-processing-data: 10
    connection-life-timeout-seconds: 300

wialon:
  server:
    host: localhost
    port: 6001
    amountThreadsToProcessConnection: 1
    amountThreadsToProcessData: 10
    aliveConnectionTimeoutSeconds: 300

data:
  validation:
    minValidAmountOfSatellites: 3
    maxValidAmountOfSatellites: 999
    minValidDateTime: 2010-01-01 00:00:00
    maxValidDateTimeDeltaSecondsFromNow: 15

kafka:
  topic:
    inbound-data:
      name: inbound-data
      partitions-amount: 1
      replication-factor: 3
      producer:
        batch-size: 10
        linger-ms: 500
        delivery-timeout-ms: 100000
      consumer:
        group-id: inbound-data-group
        max-poll-records: 400
        fetch-max-wait-ms: 1000
        fetch-min-bytes: 10000
    saved-data:
      name: saved-data
      partitions-amount: 1
      replication-factor: 3
      producer:
        batch-size: 10
        linger-ms: 500
        delivery-timeout-ms: 100000
      consumer:
        group-id: saved-data-group
        max-poll-records: 400
        fetch-max-wait-ms: 1000
        fetch-min-bytes: 10000

nominatim:
  reverse:
    url:
      template: https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=%f&lon=%f&zoom=10&accept-language=ru&polygon_geojson=1&extratags=1
  millis-between-requests: 1000
  enable-waiting-between-requests: true

searching-cities:
  handled-point-count-to-save-state: 10
  thread-count: 5

track-simplifier:
  ramer-douglas-peucker:
    epsilon: 0.0015

mileage-calculator:
  enable-accurate-calculator: false

tracker-server:
  data-default-property:
    course: 0
    altitude: 0
    speed: 0
    amount-of-satellites: 3
    hdop: 5
    inputs: 0
    outputs: 0
    driver-key-code: not defined




