spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wialon_transport
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
    show-sql: true
  kafka:
    bootstrap-servers: 127.0.0.1:9092
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

wialon:
  server:
    host: localhost
    port: 6001
    amountThreadsToProcessConnection: 1
    amountThreadsToProcessData: 10
    aliveConnectionTimeoutSeconds: 300

data:
  validation:
    minValidAmountOfSatellites: 3
    maxValidAmountSatellites: 999
    minValidDateTime: 2010-01-01 00:00:00
    deltaSecondsFromNowMaxAllowableValidDateTime: 15
    minValidDOP: 0
    maxValidDOP: 7

data-fixing:
  enable: false

data-filtering:
  enable: false

kafka:
  topic:
    inbound-data:
      name: inbound-data
      partitions-amount: 1
      replication-factor: 3
      producer:
        batch-size: 10
        linger-ms: 500
        delivery-timeout-ms: 100000
      consumer:
        group-id: inbound-data-group
        max-poll-records: 400
        fetch-max-wait-ms: 1000
        fetch-min-bytes: 10000
    saved-data:
      name: saved-data
      partitions-amount: 1
      replication-factor: 3
      producer:
        batch-size: 10
        linger-ms: 500
        delivery-timeout-ms: 100000
      consumer:
        group-id: saved-data-group
        max-poll-records: 400
        fetch-max-wait-ms: 1000
        fetch-min-bytes: 10000

nominatim:
  reverse:
    url:
      template: https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=%f&lon=%f&zoom=10&accept-language=ru&polygon_geojson=1&extratags=1
  millis-between-requests: 1000
  enable-waiting-between-requests: true

search-cities:
  amount-handled-points-to-save-state: 10
  amount-of-threads-to-search-cities: 5

track-simplifier:
  ramer-douglas-peucker:
    epsilon: 0.0015




